AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2

  Exclude:
    - "**/vendor/**/*"
    - "**/tmp/**/*"
    - "**/bin/**/*"
    - "**/plugins/**/*"
    - "**/extra/**/*"
    - "**/lib/generators/**/templates/*"
    - "**/lib/tasks/**/*"
    - "**/files/**/*"
    - "db/schema.rb"

# Enable extensions

require:
  - rubocop-performance
  - rubocop-rails
